### ISSUE TITLE
bug while compiling a less.js file

### ISSUE THREAD

**Issue by spielerinternet** [bdkjones/CodeKit-1-Old#127]
TypeError: Cannot call method 'map' of undefined
    at Object.eval (/Applications/CodeKit.app/Contents/Resources/engines/less/lib/less/tree/mixin.js:33:54)
    at Object.eval (/Applications/CodeKit.app/Contents/Resources/engines/less/lib/less/tree/ruleset.js:40:75)
    at Object.eval (/Applications/CodeKit.app/Contents/Resources/engines/less/lib/less/tree/ruleset.js:49:53)
    at Object.toCSS (/Applications/CodeKit.app/Contents/Resources/engines/less/lib/less/parser.js:313:44)
    at /Applications/CodeKit.app/Contents/Resources/engines/less/bin/lessc:103:28
    at Object.parse (/Applications/CodeKit.app/Contents/Resources/engines/less/lib/less/parser.js:387:17)
    at /Applications/CodeKit.app/Contents/Resources/engines/less/bin/lessc:97:8
    at [object Object].<anonymous> (fs.js:107:5)
    at [object Object].emit (events.js:61:17)
    at afterRead (fs.js:878:12)

I cannot find a error in the less.js-file.

**Comment by spielerinternet** [comment]
well, it was a bug in my less-code. But this log-message is irritating.

Thx for your work!

**Comment by bdkjones** [comment]
I'm assuming this is no longer an issue.
