### ISSUE TITLE
Some files which compile with Less.app don't with CodeKit

### ISSUE THREAD

**Issue by paulyoung** [bdkjones/CodeKit-1-Old#38]
Seeing this error in CodeKit, compiles just fine in Less.app - will try and figure out why.

```
TypeError: Object #<Object> has no method 'toCSS'
    at /Applications/CodeKit.app/Contents/Resources/engines/less/lib/less/tree/expression.js:18:22
    at Array.map (native)
    at Object.toCSS (/Applications/CodeKit.app/Contents/Resources/engines/less/lib/less/tree/expression.js:17:27)
    at /Applications/CodeKit.app/Contents/Resources/engines/less/lib/less/tree/mixin.js:33:52
    at Array.map (native)
    at Object.eval (/Applications/CodeKit.app/Contents/Resources/engines/less/lib/less/tree/mixin.js:32:54)
    at Object.eval (/Applications/CodeKit.app/Contents/Resources/engines/less/lib/less/tree/ruleset.js:39:75)
    at Object.eval (/Applications/CodeKit.app/Contents/Resources/engines/less/lib/less/tree/ruleset.js:48:53)
    at Object.eval (/Applications/CodeKit.app/Contents/Resources/engines/less/lib/less/tree/ruleset.js:48:53)
    at Object.eval (/Applications/CodeKit.app/Contents/Resources/engines/less/lib/less/tree/ruleset.js:48:53)
```

**Comment by bdkjones** [comment]
Interesting. 

This is not an issue with the app; this is an issue with Less.js. The currently shipping version of Less.app is using a slightly older version of Less.js. 

There may be a bug in the latest version of Less.

**Comment by paulyoung** [comment]
For sure. Seems to be a conflict with a mixin and a class name:

```
input.button {
    .button();
}
```

**Comment by bdkjones** [comment]
Look at the Less.js issues page. I seem to remember seeing something about this there.
