### ISSUE TITLE
v1.6.2 failed on markdown in jade?!?!

### ISSUE THREAD

**Issue by bigfat** [bdkjones/CodeKit-1-Old#604]
just as subject

**Comment by bdkjones** [comment]
_sigh_ another update, another issue with Jade. Please send me an example file I can test with. Thanks!

**Comment by bigfat** [comment]
here's attached example jade.

anyway i've solve this temporarily, by force CodeKit using /users/me/node_modules/jade/bin/jade

(sorry i dunno how to check the version number, i'm not familiar with these stuff...)

thank you for soon reply!
- dp

**Comment by bigfat** [comment]
sorry! just sent a wrong jade file,
please use this newest attachment.
- dp

**Comment by maniacyak** [comment]
I'm seeing this issue too, specifically when attempting to `include` an HTML file. Here's the error message from CodeKit:

```
/Applications/CodeKit.app/Contents/Resources/engines/jade/lib/runtime.js:174
  throw err;
        ^
TypeError: (redacted).jade:69
    67|         .watch-list-sidetab
    68| 
  > 69| include footer.html

Object #<Object> has no method 'exists'
    at Object.Parser.parseInclude (/Applications/CodeKit.app/Contents/Resources/engines/jade/lib/parser.js:493:19)
    at Object.Parser.parseExpr (/Applications/CodeKit.app/Contents/Resources/engines/jade/lib/parser.js:241:21)
    at Object.Parser.parse (/Applications/CodeKit.app/Contents/Resources/engines/jade/lib/parser.js:133:25)
    at parse (/Applications/CodeKit.app/Contents/Resources/engines/jade/lib/jade.js:100:62)
    at Object.exports.compile (/Applications/CodeKit.app/Contents/Resources/engines/jade/lib/jade.js:161:9)
    at /Applications/CodeKit.app/Contents/Resources/engines/jade/bin/jade:144:23
    at fs.js:266:14
    at Object.oncomplete (fs.js:107:15)
```

Codekit -> About reports Jade as 0.30.0, but a quick folder diff suggests `CodeKit.app/Contents/Resources/engines/jade/lib/filters.js` is very different from the [version on GitHub](https://github.com/visionmedia/jade/blob/0.30.0/lib/filters.js), and lacks the following:

```
filter.exists = function (name, str, options) {
  return typeof filter[name] === 'function' || transformers[name];
};
```

HTH

**Comment by bdkjones** [comment]
Yep. This is a known issue because Jade completely changed how it deals with "filters" in 0.30.0. I'm working on a workaround for Jade's new crazy approach. In the meantime, you can get this working by installing Jade at the command line (along with markdown, less, coffeescript or whatever language you're trying to import) and then switching CodeKit to use that external Jade compiler --> Preferences > Languages > Jade > Advanced Compiler Settings
