### ISSUE TITLE
Unable to compile after updating to Mac OS X 10.9

### ISSUE THREAD

**Issue by NSBrianWard** [bdkjones/CodeKit-1-Old#614]
Hi there! Love the product. Just bought it a few days ago. Everything was working great, then I upgraded to the dev build of 10.9 and am now getting this error barf on compile... (tried doing a clean project and didn't seem to fix. anything i can do short of reverting back to 10.8?):

Compass was unable to compile one or more files in the project: 

/Applications/CodeKit.app/Contents/Resources/engines/oilypng/lib/oily_png/oily_png.bundle: [BUG] Segmentation fault
ruby 2.0.0p195 (2013-05-14 revision 40734) [universal.x86_64-darwin13]

-- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:
     \* ~/Library/Logs/CrashReporter
     \* /Library/Logs/CrashReporter
     \* ~/Library/Logs/DiagnosticReports
     \* /Library/Logs/DiagnosticReports
   the more detail of.

-- Control frame information -----------------------------------------------
c:0027 p:-17525236194490 s:0133 e:000132 TOP    [FINISH]
c:0026 p:---- s:0131 e:000130 CFUNC  :require
c:0025 p:0073 s:0127 e:000126 METHOD /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45
c:0024 p:0025 s:0117 e:000116 TOP    /Applications/CodeKit.app/Contents/Resources/engines/oilypng/lib/oily_png.rb:19 [FINISH]
c:0023 p:---- s:0115 e:000114 CFUNC  :require
c:0022 p:0073 s:0111 e:000110 METHOD /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45
c:0021 p:0009 s:0101 e:000100 TOP    /Applications/CodeKit.app/Contents/Resources/engines/compass/lib/compass/sass_extensions/sprites/engines/chunky_png_engine.rb:2 [FINISH]
c:0020 p:---- s:0099 e:000098 CFUNC  :require
c:0019 p:0073 s:0095 e:000094 METHOD /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45
c:0018 p:0017 s:0085 e:000084 TOP    /Applications/CodeKit.app/Contents/Resources/engines/compass/lib/compass/sass_extensions/sprites/engines.rb:25 [FINISH]
c:0017 p:---- s:0083 e:000082 CFUNC  :require
c:0016 p:0073 s:0079 e:000078 METHOD /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45
c:0015 p:0089 s:0069 e:000068 TOP    /Applications/CodeKit.app/Contents/Resources/engines/compass/lib/compass/sass_extensions/sprites.rb:18 [FINISH]
c:0014 p:---- s:0067 e:000066 CFUNC  :require
c:0013 p:0073 s:0063 e:000062 METHOD /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45
c:0012 p:0076 s:0053 e:000052 TOP    /Applications/CodeKit.app/Contents/Resources/engines/compass/lib/compass/sass_extensions.rb:10 [FINISH]
c:0011 p:---- s:0051 e:000050 CFUNC  :require
c:0010 p:0073 s:0047 e:000046 METHOD /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45
c:0009 p:0014 s:0037 e:000036 BLOCK  /Applications/CodeKit.app/Contents/Resources/engines/compass/lib/compass.rb:5 [FINISH]
c:0008 p:---- s:0034 e:000033 CFUNC  :each
c:0007 p:0032 s:0031 e:000030 TOP    /Applications/CodeKit.app/Contents/Resources/engines/compass/lib/compass.rb:4 [FINISH]
c:0006 p:---- s:0029 e:000028 CFUNC  :require
c:0005 p:0073 s:0025 e:000024 METHOD /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45
c:0004 p:0009 s:0015 e:000014 BLOCK  /Applications/CodeKit.app/Contents/Resources/engines/compass/bin/compass:33
c:0003 p:0014 s:0013 e:000012 METHOD /Applications/CodeKit.app/Contents/Resources/engines/compass/bin/compass:21
c:0002 p:0257 s:0008 E:0009d8 EVAL   /Applications/CodeKit.app/Contents/Resources/engines/compass/bin/compass:32 [FINISH]
c:0001 p:0000 s:0002 E:001e68 TOP    [FINISH]

/Applications/CodeKit.app/Contents/Resources/engines/compass/bin/compass:32:in `<main>'
/Applications/CodeKit.app/Contents/Resources/engines/compass/bin/compass:21:in`fallback_load_path'
/Applications/CodeKit.app/Contents/Resources/engines/compass/bin/compass:33:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in`require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
/Applications/CodeKit.app/Contents/Resources/engines/compass/lib/compass.rb:4:in`<top (required)>'
/Applications/CodeKit.app/Contents/Resources/engines/compass/lib/compass.rb:4:in `each'
/Applications/CodeKit.app/Contents/Resources/engines/compass/lib/compass.rb:5:in`block in <top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in`require'
/Applications/CodeKit.app/Contents/Resources/engines/compass/lib/compass/sass_extensions.rb:10:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in`require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
/Applications/CodeKit.app/Contents/Resources/engines/compass/lib/compass/sass_extensions/sprites.rb:18:in`<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in`require'
/Applications/CodeKit.app/Contents/Resources/engines/compass/lib/compass/sass_extensions/sprites/engines.rb:25:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in`require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
/Applications/CodeKit.app/Contents/Resources/engines/compass/lib/compass/sass_extensions/sprites/engines/chunky_png_engine.rb:2:in`<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in`require'
/Applications/CodeKit.app/Contents/Resources/engines/oilypng/lib/oily_png.rb:19:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in`require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'

-- C level backtrace information -------------------------------------------

-- Other runtime information -----------------------------------------------
- Loaded script: /Applications/CodeKit.app/Contents/Resources/engines/compass/bin/compass
- Loaded features:
  
  0 enumerator.so
  1 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin13/enc/encdb.bundle
  2 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin13/enc/trans/transdb.bundle
  3 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin13/rbconfig.rb
  4 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/compatibility.rb
  5 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/defaults.rb
  6 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/deprecate.rb
  7 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/errors.rb
  8 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/version.rb
  9 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/requirement.rb
  10 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/platform.rb
  11 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb
  12 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/exceptions.rb
  13 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_gem.rb
  14 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb
  15 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems.rb
  16 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/path_support.rb
  17 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb
  18 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin13/date_core.bundle
  19 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/date/format.rb
  20 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/date.rb
  21 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/cgi/util.rb
  22 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin13/strscan.bundle
  23 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/erb.rb
  24 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/set.rb
  25 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin13/stringio.bundle
  26 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/root.rb
  27 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/util/subset_map.rb
  28 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/util/multibyte_string_scanner.rb
  29 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/util.rb
  30 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/version.rb
  31 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/logger/log_level.rb
  32 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/logger/base.rb
  33 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/logger.rb
  34 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin13/digest.bundle
  35 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/digest.rb
  36 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin13/digest/sha1.bundle
  37 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/cache_stores/base.rb
  38 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin13/etc.bundle
  39 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb
  40 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/cache_stores/filesystem.rb
  41 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/cache_stores/memory.rb
  42 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/cache_stores/chain.rb
  43 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/cache_stores.rb
  44 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/tree/node.rb
  45 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/tree/root_node.rb
  46 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin13/pathname.bundle
  47 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb
  48 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/common.rb
  49 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/generic.rb
  50 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/ftp.rb
  51 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/http.rb
  52 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/https.rb
  53 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/ldap.rb
  54 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/ldaps.rb
  55 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/mailto.rb
  56 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri.rb
  57 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/tree/rule_node.rb
  58 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/tree/comment_node.rb
  59 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/tree/prop_node.rb
  60 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/tree/directive_node.rb
  61 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/tree/media_node.rb
  62 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/tree/supports_node.rb
  63 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/tree/css_import_node.rb
  64 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/tree/variable_node.rb
  65 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/tree/mixin_def_node.rb
  66 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/tree/mixin_node.rb
  67 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/tree/trace_node.rb
  68 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/tree/content_node.rb
  69 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/tree/function_node.rb
  70 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/tree/return_node.rb
  71 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/tree/extend_node.rb
  72 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/tree/if_node.rb
  73 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/tree/while_node.rb
  74 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/tree/for_node.rb
  75 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/tree/each_node.rb
  76 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/tree/debug_node.rb
  77 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/tree/warn_node.rb
  78 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/tree/import_node.rb
  79 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/tree/charset_node.rb
  80 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/tree/visitors/base.rb
  81 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/tree/visitors/perform.rb
  82 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/tree/visitors/cssize.rb
  83 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/tree/visitors/extend.rb
  84 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/tree/visitors/convert.rb
  85 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/tree/visitors/to_css.rb
  86 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/tree/visitors/deep_copy.rb
  87 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/tree/visitors/set_options.rb
  88 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/tree/visitors/check_nesting.rb
  89 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/selector/simple.rb
  90 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/selector/abstract_sequence.rb
  91 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/selector/comma_sequence.rb
  92 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/selector/sequence.rb
  93 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/selector/simple_sequence.rb
  94 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/selector.rb
  95 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/environment.rb
  96 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/script/node.rb
  97 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/script/variable.rb
  98 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/script/functions.rb
  99 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/script/funcall.rb
  100 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/script/number.rb
  101 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/script/color.rb
  102 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/script/bool.rb
  103 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/script/null.rb
  104 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/script/list.rb
  105 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/script/arg_list.rb
  106 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/script/literal.rb
  107 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/script/string.rb
  108 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/script/unary_operation.rb
  109 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/script/interpolation.rb
  110 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/script/string_interpolation.rb
  111 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/script/operation.rb
  112 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/scss/rx.rb
  113 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/script/lexer.rb
  114 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/script/parser.rb
  115 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/script.rb
  116 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/scss/script_lexer.rb
  117 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/scss/script_parser.rb
  118 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/scss/parser.rb
  119 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/script/css_lexer.rb
  120 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/script/css_parser.rb
  121 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/scss/static_parser.rb
  122 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/scss/css_parser.rb
  123 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/scss.rb
  124 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/error.rb
  125 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/importers/base.rb
  126 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/importers/filesystem.rb
  127 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/importers.rb
  128 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/shared.rb
  129 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/media.rb
  130 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/supports.rb
  131 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/engine.rb
  132 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/railtie.rb
  133 /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass.rb
  134 /Applications/CodeKit.app/Contents/Resources/engines/compass/lib/compass/dependencies.rb
  135 /Applications/CodeKit.app/Contents/Resources/engines/compass/lib/compass/util.rb
  136 /Applications/CodeKit.app/Contents/Resources/engines/compass/lib/compass/browser_support.rb
  137 /Applications/CodeKit.app/Contents/Resources/engines/compass/lib/compass/sass_extensions/functions/selectors.rb
  138 /Applications/CodeKit.app/Contents/Resources/engines/compass/lib/compass/sass_extensions/functions/enumerate.rb
  139 /Applications/CodeKit.app/Contents/Resources/engines/compass/lib/compass/sass_extensions/functions/urls.rb
  140 /Applications/CodeKit.app/Contents/Resources/engines/compass/lib/compass/sass_extensions/functions/display.rb
  141 /Applications/CodeKit.app/Contents/Resources/engines/compass/lib/compass/sass_extensions/functions/inline_image.rb
  142 /Applications/CodeKit.app/Contents/Resources/engines/compass/lib/compass/sass_extensions/functions/image_size.rb
  143 /Applications/CodeKit.app/Contents/Resources/engines/compass/lib/compass/sass_extensions/functions/constants.rb
  144 /Applications/CodeKit.app/Contents/Resources/engines/compass/lib/compass/sass_extensions/functions/gradient_support.rb
  145 /Applications/CodeKit.app/Contents/Resources/engines/compass/lib/compass/sass_extensions/functions/font_files.rb
  146 /Applications/CodeKit.app/Contents/Resources/engines/compass/lib/compass/sass_extensions/functions/lists.rb
  147 /Applications/CodeKit.app/Contents/Resources/engines/compass/lib/compass/sass_extensions/functions/colors.rb
  148 /Applications/CodeKit.app/Contents/Resources/engines/compass/lib/compass/sass_extensions/functions/math.rb
  149 /Applications/CodeKit.app/Contents/Resources/engines/compass/lib/compass/sass_extensions/functions/sprites.rb
  150 /Applications/CodeKit.app/Contents/Resources/engines/compass/lib/compass/sass_extensions/functions/env.rb
  151 /Applications/CodeKit.app/Contents/Resources/engines/compass/lib/compass/sass_extensions/functions/cross_browser_support.rb
  152 /Applications/CodeKit.app/Contents/Resources/engines/compass/lib/compass/sass_extensions/functions.rb
  153 /Applications/CodeKit.app/Contents/Resources/engines/compass/lib/compass/sass_extensions/monkey_patches/traversal.rb
  154 /Applications/CodeKit.app/Contents/Resources/engines/compass/lib/compass/sass_extensions/monkey_patches/browser_support.rb
  155 /Applications/CodeKit.app/Contents/Resources/engines/compass/lib/compass/sass_extensions/monkey_patches.rb
  156 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin13/digest/md5.bundle
  157 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/ostruct.rb
  158 /Applications/CodeKit.app/Contents/Resources/engines/compass/lib/compass/sprite_importer/binding.rb
  159 /Applications/CodeKit.app/Contents/Resources/engines/compass/lib/compass/sprite_importer.rb
  160 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/forwardable.rb
  161 /Applications/CodeKit.app/Contents/Resources/engines/compass/lib/compass/sass_extensions/sprites/image_row.rb
  162 /Applications/CodeKit.app/Contents/Resources/engines/compass/lib/compass/sass_extensions/sprites/row_fitter.rb
  163 /Applications/CodeKit.app/Contents/Resources/engines/compass/lib/compass/sass_extensions/sprites/image.rb
  164 /Applications/CodeKit.app/Contents/Resources/engines/compass/lib/compass/sass_extensions/sprites/layout_methods.rb
  165 /Applications/CodeKit.app/Contents/Resources/engines/compass/lib/compass/sass_extensions/sprites/sprite_methods.rb
  166 /Applications/CodeKit.app/Contents/Resources/engines/compass/lib/compass/sass_extensions/sprites/image_methods.rb
  167 /Applications/CodeKit.app/Contents/Resources/engines/compass/lib/compass/sass_extensions/sprites/sprite_map.rb
  168 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin13/zlib.bundle
  169 /Applications/CodeKit.app/Contents/Resources/engines/chunkypng/lib/chunky_png/compatibility.rb
  170 /Applications/CodeKit.app/Contents/Resources/engines/chunkypng/lib/chunky_png/datastream.rb
  171 /Applications/CodeKit.app/Contents/Resources/engines/chunkypng/lib/chunky_png/chunk.rb
  172 /Applications/CodeKit.app/Contents/Resources/engines/chunkypng/lib/chunky_png/palette.rb
  173 /Applications/CodeKit.app/Contents/Resources/engines/chunkypng/lib/chunky_png/color.rb
  174 /Applications/CodeKit.app/Contents/Resources/engines/chunkypng/lib/chunky_png/point.rb
  175 /Applications/CodeKit.app/Contents/Resources/engines/chunkypng/lib/chunky_png/vector.rb
  176 /Applications/CodeKit.app/Contents/Resources/engines/chunkypng/lib/chunky_png/dimension.rb
  177 /Applications/CodeKit.app/Contents/Resources/engines/chunkypng/lib/chunky_png/canvas/png_encoding.rb
  178 /Applications/CodeKit.app/Contents/Resources/engines/chunkypng/lib/chunky_png/canvas/png_decoding.rb
  179 /Applications/CodeKit.app/Contents/Resources/engines/chunkypng/lib/chunky_png/canvas/adam7_interlacing.rb
  180 /Applications/CodeKit.app/Contents/Resources/engines/chunkypng/lib/chunky_png/canvas/stream_exporting.rb
  181 /Applications/CodeKit.app/Contents/Resources/engines/chunkypng/lib/chunky_png/canvas/stream_importing.rb
  182 /Applications/CodeKit.app/Contents/Resources/engines/chunkypng/lib/chunky_png/canvas/data_url_exporting.rb
  183 /Applications/CodeKit.app/Contents/Resources/engines/chunkypng/lib/chunky_png/canvas/data_url_importing.rb
  184 /Applications/CodeKit.app/Contents/Resources/engines/chunkypng/lib/chunky_png/canvas/operations.rb
  185 /Applications/CodeKit.app/Contents/Resources/engines/chunkypng/lib/chunky_png/canvas/drawing.rb
  186 /Applications/CodeKit.app/Contents/Resources/engines/chunkypng/lib/chunky_png/canvas/resampling.rb
  187 /Applications/CodeKit.app/Contents/Resources/engines/chunkypng/lib/chunky_png/canvas/masking.rb
  188 /Applications/CodeKit.app/Contents/Resources/engines/chunkypng/lib/chunky_png/canvas.rb
  189 /Applications/CodeKit.app/Contents/Resources/engines/chunkypng/lib/chunky_png/image.rb
  190 /Applications/CodeKit.app/Contents/Resources/engines/chunkypng/lib/chunky_png.rb

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html

**Comment by NSBrianWard** [comment]
Alright, got a workaround for this. It appears that we're defaulting to Ruby 2 in 10.9. Changing the default version back to 1.8 (replaced the "Current" soft link!) fixed this one. Don't know much about Ruby, but something must have changed in 2 that breaks CodeKit.

**Comment by mikestecker** [comment]
@primedirective how were you able to switch ruby versions?

**Comment by NSBrianWard** [comment]
Pop in to /System/Library/Frameworks/Ruby.framework/versions and change the "Current" soft link to point to 1.8 instead of 2.0. You can set it with: sudo ln -s 1.8 Current

Pretty sure that would work with the original file, but i renamed the one that was there and used touch to make a new file called current in the same location.

Good luck!

**Comment by mikestecker** [comment]
@primedirective that did the trick. Thanks!

**Comment by NSBrianWard** [comment]
Glad to hear that fixed it! :D

**Comment by naoufal** [comment]
@primedirective was having the same problem.  Thanks for the fix.
